### ISSUE TITLE
Seed loss when Pay for seeds is off

### ISSUE THREAD

**Issue by AndreKR** [Thorinair/Stardew-Profits#32]
When "Pay for seeds" is enabled, the profit is calculated from the number of fruits that can be harvested and the seed loss to buy the seeds. When it is disabled, the same number is used but the seed loss is zeroed. So where do the seeds come from?

Instead, I think when "Pay for seeds" is disabled, it should reduce the number of harvested fruits by the number of fruits that are necessary to make the same number of seeds in the seed maker.

**Comment by FinalDoom** [comment]
This sounds like a good suggestion -- I'd add a third option to "pay for seeds", such that you have pay/seed maker/ignore. I think You can reasonably use probabilities for seed maker calculations, though I think it's pretty random. I'll have to look at the code.

**Comment by Thorinair** [comment]
This change is a bit more problematic to implement because it requires some clever thinking. Seed maker makes around 2 seeds per average, but you cannot count on that. Also, what happens when there is just 1 planted crop? All of the produce will become a seed, one you can sell (as a seed), one you can replant for another. Would it need to enforce only planting even number of crops so you can convert half to seeds for replanting and sell the other half?

I can implement something, but I would like to discuss the best possible solution as it is quite a complex problem, and also possibly quite a deceiving one, as one could get only 1 seed 4 times in a row for 0 profit.

**Comment by Thorinair** [comment]
Considering what was said here, I implemented a first version of this feature on live now. It is called "Process & Replant". Enabling it forces the crops to be an even number and will automatically calculate for all produces.
