### ISSUE TITLE
Ancient Fruit not working

### ISSUE THREAD

**Issue by StefanOssendorf** [Thorinair/Stardew-Profits#44]
Hi. I stumbled upon your awesome calculator but somehow the ancient fruit seems not to work. Regardless of my setting it's shown with 0.
![image](https://user-images.githubusercontent.com/5385401/146827638-d110a0ad-ed75-489f-8ce9-85d03c2784f5.png)

Thanks in advance
Stefan

**Comment by Thorinair** [comment]
This is because a single Ancient Fruit cannot grow during one season as currently selected, but it can during two. However, even choosing "Cross season" in this situation won't help, as it crosses over to winter, so it will die out as soon as it hits day one. You can grow the fruit any of the following situations however:

- Sprint + Cross season
- Summer + Cross season
- Greenhouse

**Comment by StefanOssendorf** [comment]
@Thorinair Thanks for your quick answer and you are of course completely right! Did not think about winter (or using cross season). But just selecting "Greenhouse" won't do in that case either, since I forgot to change the Number of days.
Maybe selecting Greenhouse should default Number of Days to 112?

Anyway you solved it for me :-) Thanks again!
