### ISSUE TITLE
Wine aging in casks x2 wine value

### ISSUE THREAD

**Issue by andreaslopez** [Thorinair/Stardew-Profits#52]
In summer with kegs, Hops seem as the most profitable crop. But if you consider aging the starfruit wine it doubles. So it would be the most profitable.

**Comment by Thorinair** [comment]
This is now implemented in the dev build! Soon to be pushed to live.
One thing I've noticed is that the difference between Hops and Starfruit becomes visible only after like day 11 or so. This is because Hops keep regrowing every day and it accumulates as still more valuable than Starfruit if planted at start of spring...
